### ISSUE TITLE
`mustermann (1.0.3)` won't work with Ruby 3.2

### ISSUE THREAD

**Issue by Fuzzwah** [github-developer/creating-ci-tests-with-the-checks-api#21]
```
/usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann/regular.rb:22:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `block in new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann/equality_map.rb:43:in `fetch'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann.rb:67:in `new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `block in new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `map'
	from /usr/local/lib/ruby/gems/3.2.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `new'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1641:in `compile'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1629:in `compile!'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1271:in `error'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1838:in `<class:Base>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:894:in `<module:Sinatra>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:22:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/main.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra/main.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.2.0/gems/sinatra-2.0.4/lib/sinatra.rb:1:in `<top (required)>'
	from template_server.rb:1:in `require'
	from template_server.rb:1:in `<main>'
```

**Comment by shiyuhang0** [comment]
meet the same error. 
I upgrade the octokit in order to support check API. octokit 6.0 need ruby >=2.7, so I upgrade ruby to 3.2. then I find mustermann can not work with it.

Any workaround now?

**Comment by horatiothomas** [comment]
OP created a pr: https://github.com/github-developer/creating-ci-tests-with-the-checks-api/pull/22
